// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebarsTutorials = {
  tutorialsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebarsTutorials;
