// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  networkSidebar: [
    {
      type: 'doc',
      id: 'Network/index',
      label: 'Network Overview',
    },
    {
      type: 'category',
      label: 'Cellular',
      collapsed: false,
      collapsible: true,
      link: { type: 'doc', id: 'Network/Cellular/Cellular_Intro' },
      items: [
        {
          type: 'category',
          label: 'KSE-91A',
          collapsed: false,
          collapsible: true,
          link: { type: 'generated-index',
                  title: 'KSE-91A',
                  description: 'KSE-91A documentation',
                },
          items: [
            { type: 'doc', id: 'Network/Cellular/KSE-91A/KSE-91A_Overview', label: 'Overview' },
            { type: 'doc', id: 'Network/Cellular/KSE-91A/KSE-91A_Quick_Start', label: 'Quick Start' },
            { type: 'doc', id: 'Network/Cellular/KSE-91A/KSE-91A_AT_Commands', label: 'AT Commands' },
            { type: 'doc', id: 'Network/Cellular/KSE-91A/KSE-91A_FAQ', label: 'FAQ' },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'LPWAN',
      collapsed: true,
      collapsible: true,
      link: { type: 'doc', id: 'Network/LPWAN/LPWAN_Intro' },
      items: [],
    },
    {
      type: 'category',
      label: 'WiFi',
      collapsed: true,
      collapsible: true,
      link: { type: 'doc', id: 'Network/WiFi/WiFi_Intro' },
      items: [],
    },
    {
      type: 'category',
      label: 'Bluetooth',
      collapsed: true,
      collapsible: true,
      link: { type: 'doc', id: 'Network/Bluetooth/Bluetooth_Intro' },
      items: [],
    },
    {
      type: 'category',
      label: 'Ethernet',
      collapsed: true,
      collapsible: true,
      link: { type: 'doc', id: 'Network/Ethernet/Ethernet_Intro' },
      items: [],
    },
    {
      type: 'category',
      label: 'Satellite',
      collapsed: true,
      collapsible: true,
      link: { type: 'doc', id: 'Network/Satellite/Satellite_Intro' },
      items: [],
    },
  ],

  tutorialsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'Tutorials',
    },
  ],
};

export default sidebars;